# Generated by Django 4.0.8 on 2023-06-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_watchdog', '0002_auto_20141029_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='levelname',
            field=models.CharField(editable=False, max_length=20, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='message',
            field=models.TextField(editable=False, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='request_repr',
            field=models.TextField(editable=False, verbose_name='Request representation'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='shortmessage',
            field=models.CharField(editable=False, max_length=256, verbose_name='Short message'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When'),
        ),
    ]
